#pragma once

#include "types.h"
#include "platform/i386/port.h"
#include "platform/i386/interrupts.h"

// Define keyboard read port
#define KEYBOARD_PORT 0x60

// Enumeration for keyboard key
enum KEYBOARD_KEYTABLE {
    KEYBOARD_KEY_ESCAPE         = 0x01,
    KEYBOARD_KEY_1              = 0x02,
    KEYBOARD_KEY_2              = 0x03,
    KEYBOARD_KEY_3              = 0x04,
    KEYBOARD_KEY_4              = 0x05,
    KEYBOARD_KEY_5              = 0x06,
    KEYBOARD_KEY_6              = 0x07,
    KEYBOARD_KEY_7              = 0x08,
    KEYBOARD_KEY_8              = 0x09,
    KEYBOARD_KEY_9              = 0x0A,
    KEYBOARD_KEY_0              = 0x0B,
    KEYBOARD_KEY_MINUS          = 0x0C,
    KEYBOARD_KEY_EQUAL          = 0x0D,
    KEYBOARD_KEY_BACKSPACE      = 0x0E,
    KEYBOARD_KEY_TAB            = 0x0F,
    KEYBOARD_KEY_Q              = 0x10,
    KEYBOARD_KEY_W              = 0x11,
    KEYBOARD_KEY_E              = 0x12,
    KEYBOARD_KEY_R              = 0x13,
    KEYBOARD_KEY_T              = 0x14,
    KEYBOARD_KEY_Y              = 0x15,
    KEYBOARD_KEY_U              = 0x16,
    KEYBOARD_KEY_I              = 0x17,
    KEYBOARD_KEY_O              = 0x18,
    KEYBOARD_KEY_P              = 0x19,
    KEYBOARD_KEY_LBRACKET       = 0x1A,
    KEYBOARD_KEY_RBRACKET       = 0x1B,
    KEYBOARD_KEY_ENTER          = 0x1C,
    KEYBOARD_KEY_LEFT_CTRL      = 0x1D,
    KEYBOARD_KEY_A              = 0x1E,
    KEYBOARD_KEY_S              = 0x1F,
    KEYBOARD_KEY_D              = 0x20,
    KEYBOARD_KEY_F              = 0x21,
    KEYBOARD_KEY_G              = 0x22,
    KEYBOARD_KEY_H              = 0x23,
    KEYBOARD_KEY_J              = 0x24,
    KEYBOARD_KEY_K              = 0x25,
    KEYBOARD_KEY_L              = 0x26,
    KEYBOARD_KEY_SEMICOLON      = 0x27,
    KEYBOARD_KEY_QUOTE          = 0x28,
    KEYBOARD_KEY_BACKTICK       = 0x29,
    KEYBOARD_KEY_LEFT_SHIFT     = 0x2A,
    KEYBOARD_KEY_BACKSLASH      = 0x2B,
    KEYBOARD_KEY_Z              = 0x2C,
    KEYBOARD_KEY_X              = 0x2D,
    KEYBOARD_KEY_C              = 0x2E,
    KEYBOARD_KEY_V              = 0x2F,
    KEYBOARD_KEY_B              = 0x30,
    KEYBOARD_KEY_N              = 0x31,
    KEYBOARD_KEY_M              = 0x32,
    KEYBOARD_KEY_COMMA          = 0x33,
    KEYBOARD_KEY_DOT            = 0x34,
    KEYBOARD_KEY_SLASH          = 0x35,
    KEYBOARD_KEY_RIGHT_SHIFT    = 0x36,
    KEYBOARD_KEY_ASTERISK       = 0x37,
    KEYBOARD_KEY_LEFT_ALT       = 0x38,
    KEYBOARD_KEY_SPACE          = 0x39,
    KEYBOARD_KEY_CAPSLOCK       = 0x3A,
    KEYBOARD_KEY_F1             = 0x3B,
    KEYBOARD_KEY_F2             = 0x3C,
    KEYBOARD_KEY_F3             = 0x3D,
    KEYBOARD_KEY_F4             = 0x3E,
    KEYBOARD_KEY_F5             = 0x3F,
    KEYBOARD_KEY_F6             = 0x40,
    KEYBOARD_KEY_F7             = 0x41,
    KEYBOARD_KEY_F8             = 0x42,
    KEYBOARD_KEY_F9             = 0x43,
    KEYBOARD_KEY_F10            = 0x44,
    KEYBOARD_KEY_NUMLOCK        = 0x45,
    KEYBOARD_KEY_SCROLLLOCK     = 0x46,
    KEYBOARD_KEY_PAD_7          = 0x47,
    KEYBOARD_KEY_PAD_8          = 0x48,
    KEYBOARD_KEY_PAD_9          = 0x49,
    KEYBOARD_KEY_PAD_MINUS      = 0x4A,
    KEYBOARD_KEY_PAD_4          = 0x4B,
    KEYBOARD_KEY_PAD_5          = 0x4C,
    KEYBOARD_KEY_PAD_6          = 0x4D,
    KEYBOARD_KEY_PAD_PLUS       = 0x4E,
    KEYBOARD_KEY_PAD_1          = 0x4F,
    KEYBOARD_KEY_PAD_2          = 0x50,
    KEYBOARD_KEY_PAD_3          = 0x51,
    KEYBOARD_KEY_PAD_0          = 0x52,
    KEYBOARD_KEY_PAD_DOT        = 0x53,
    KEYBOARD_KEY_F11            = 0x57,
    KEYBOARD_KEY_F12            = 0x58
};

// Define keyboard key type
typedef enum KEYBOARD_KEYTABLE keyboard_key_t;

// Function prototype for read key from keyboard
char keyboard_scankey();